version: '3'

services:
  app: 
    # image: sandisunandar99/tutum-hello-world:v4
    build: 
      context: .
      dockerfile: Dockerfile
    volumes: 
      - ./www:/www/
    ports:
      - "80:80"